### ISSUE TITLE
Not working with iOS9

### ISSUE THREAD

**Issue by Carlos001** [eswick/ondeviceconsole#3]
Hi,
Just noticed that on iOS9 it won't connect to the socket. Any idea how to fix this?

Thanks,
Károly

**Comment by eswick** [comment]
Is there a jailbreak out for iOS 9 yet?

**Comment by Carlos001** [comment]
Don't know. But this used to work on non-jailbroken devices, too. Now I get -1 on both socket bind() and connect() calls. Looks like Apple now protects this address.

**Comment by eswick** [comment]
I think you're thinking of rpetrich's deviceconsole. (link: github.com/rpetrich/deviceconsole)

This repository is for *on*deviceconsole. It is a console program which actually runs *on* the device, requiring it to be jailbroken.

**Comment by Carlos001** [comment]
I adapted it, and it ran just fine till iOS9. :)
Now I get errno 0x30 on the device, which means - quoting from <sys/errno.h>:
"EADDRINUSE Address already in use.  Only one usage of each address is normally permitted."
